version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    timezone: Australia/Sydney
    time: "15:00"
    day: monday
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    timezone: Australia/Sydney
    time: "15:00"
    day: monday
